### ISSUE TITLE
Error in create_empty_tables: with self.conn as conn: AttributeError: __exit__

### ISSUE THREAD

**Issue by roj4s** [cseagle/fREedom#6]
Traceback (most recent call last):
  File "fREedom.py", line 93, in <module>
    main(args)
  File "fREedom.py", line 70, in main
    db = binnavi_db.binnavi_db(args.database, args.user, args.passwd, args.dbhost)
  File "binnavi_db.py", line 31, in **init**
    self.create_empty_tables()
  File "binnavi_db.py", line 456, in create_empty_tables
    with self.conn as conn:
AttributeError: **exit**

**Comment by cseagle** [comment]
You need to upgrade to psycopg2 version 2.5 or later
